#!/bin/sh

case "$1" in
	start)
		echo "starting scull"
		/usr/bin/scull_load
		/usr/bin/module_load
		modprobe hello
		;;
	stop)
		echo "stopping scull"
		/usr/bin/scull_unload
		/usr/bin/module_unload
		rmmod hello
		;;
	*)
		echo "Usage: $0 {start|stop}"
	exit 1
esac
exit 0

